
POST http://localhost:3000/vehicle/createVehicle
Content-Type: application/json
{
   "brand": "subaru",
   // "model": "",
   "registration": "กก5555",
   // พี่อุ๊ 83 พี่ดุล 80 พี่พร 84
   "owner": 83
}



