PATCH http://localhost:3000/user/updateCustomer/78
Content-Type: application/json
{
//  "name": "ศิริวรรณ",
//  "lastName": "ศักดิ์สูง",/
//  "tel": "0889796961"
//  "sex" : "female"
"age": 1987
}
    