POST http://localhost:3000/booking/create-booking-south/?numberBooking=5&manyDay=6&date=2025-10-03
Content-Type : application/json
Accept: application/json
{
"from" : "south",
"to" : "central",
"trailer" : "1",
"province":  [1,20,21,22,23,24,25,26,27,28,45,46,47,56]

}



// south   บวก 6 วัน   1 รถไอทือ
// [1,20,21,22,23,24,25,26,27,28,46,47,56]

// isarn นับทุก 5 วัน    5 ต้าวิ่งอีสาน
// [1,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44]


// east 
// [48,49,50,51,52,53,54,55,1]
