export enum brandCarEnum {
  toyota = 'toyota',
  honda = 'honda',
  benz = 'benz',
  bmw = 'bmw',
  mg = 'mg',
  mazda = 'mazda',
  tesla = 'tesla',
  suzuki = 'suzuki',
  mitsubishi = 'mitsubishi',
  mini = 'mini',
  ford = 'ford',
  audi = 'audi',
  chevrolet = 'chevrolet',
  nissan = 'nissan',
  byd = 'byd',
  jeep = 'jeep',
  volkswagen = 'volkswagen',
  lexus = 'lexus',
  isuzu = 'isuzu',
  kia = 'kia',
  volvo = 'volvo',
  neta = 'neta',
  landrover = 'landrover',
  dummy = 'dummy',
  subaru = 'subaru',
}
