PATCH http://localhost:3000/detail/89
Content-Type: application/json
Accept: application/json 
{
   // "booking": "43"
   // "pick": "bangkok",
   // "drop": "krabi"
   "remark": "ยอดค้าง 4300 , ลงรถที่ แม็คโครบางบอน 089-9994662 ,085-212-6996"
}