PATCH http://localhost:3000/detail/80
Content-Type: application/json
Accept: application/json 
{
   // "booking": "40"
   // "drop": "bangkok",
   // "pick": "hatyai"
   "remark": "ส่งตรงข้ามสนามบินนครศรี *รถถึงแยกไชยาให้ติดต่อ คุณปอนด์ "
}