export enum DestinationEnum {
  bangkok = 'bangkok',
  // chiangmai
  ayutthaya = 'ayutthaya',
  angthong = 'angthong',
  singburi = 'singburi',
  chainat = 'chainat',
  nakhonsawan = 'nakhonsawan',
  kamphaengphet = 'kamphaengphet',
  tak = 'tak',
  lampang = 'lampang',
  lamphun = 'lamphun',
  chiangmai = 'chiangmai',
  maehongson = 'maehongson',
  //chianglai
  chiangrai = 'chiangrai',
  phichit = 'phichit',
  phitsanulok = 'phitsanulok',
  uttaradit = 'uttaradit',
  phayao = 'phayao',
  phrae = 'phrae',
  nan = 'nan',
  // south
  phetchaburi = 'phetchaburi',
  prachuap = 'prachuap',
  chumphon = 'chumphon',
  surat = 'surat',
  nakhonsi = 'nakhonsi',
  phuket = 'phuket',
  phatthalung = 'phatthalung',
  trang = 'trang',
  hatyai = 'hatyai',
  krabi = 'krabi',
  songkhla = 'songkhla',
  phangnga = 'phangnga',
  samutsakhon = 'samutsakhon',
  nakhonpathom = 'nakhonpathom',

  // isarn
  saraburi = 'saraburi',
  nakhonratchasima = 'nakhonratchasima',
  buriram = 'buriram',
  surin = 'surin',
  sisaket = 'sisaket',
  ubon = 'ubon',
  amnatcharoen = 'amnatcharoen',
  yasothon = 'yasothon',
  roiet = 'roiet',
  mahasarakham = 'mahasarakham',
  khonkaen = 'khonkaen',
  udon = 'udon',
  sakon = 'sakon',
  nakhonphanom = 'nakhonphanom',
  mukdahan = 'mukdahan',
  kalasin = 'kalasin',
  nongkhai = 'nongkhai',

  // east

  samutprakan = 'samutprakan',
  chonburi = 'chonburi',
  rayong = 'rayong',
  trat = 'trat',
  chanthaburi = 'chanthaburi',
  chachoengsao = 'chachoengsao',
  prachinburi = 'prachinburi',
  sakaeo = 'sakaeo',
}
